name: Wait 20 minutes if needed

on: 
   pull_request:
    branches:
      - main

jobs:
  check-last-deployment:
    name: Check Last Deployment Time
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Fetch Last Deployment Time
        id: fetch-last-deployment-time
        run: |
          cd $GITHUB_WORKSPACE
          git fetch origin main
          lastDeploymentTime=$(git log --merges -1 --format=%ct origin/main)
          lastDeploymentTime=$(git log --merges -1 --format=%cn origin/main)
          echo $lastDeploymentTime > lastDeploymentTime.txt
          echo "Last Deployment Time: $lastDeploymentTime"
        # Upload lastDeploymentTime.txt as an artifact
      - name: Upload lastDeploymentTime.txt as artifact
        uses: actions/upload-artifact@v2
        with:
          name: last-deployment-time
          path: lastDeploymentTime.txt


  wait-if-not-over-20-minutes:
    name: Wait for 20 minutes if needed
    runs-on: ubuntu-latest
    needs: check-last-deployment

    steps:
      # Download the artifact
      - name: Download last-deployment-time artifact
        uses: actions/download-artifact@v2
        with:
          name: last-deployment-time
          path: .

      - name: Check Time Difference
        run: |
          lastDeploymentTime=$(cat lastDeploymentTime.txt)
          currentEpochTime=$(date +%s)
          timeDifference=$((currentEpochTime - lastDeploymentTime))

          echo "Last Deployment Time: $lastDeploymentTime"
          echo "Time Difference: $timeDifference"

          if [ $timeDifference -le 1200 ]; then
            echo "Last deployment was less than 20 minutes ago. Waiting for 20 minutes."
            sleep 1200  # Sleep for 20 minutes (1200 seconds)
          else
            echo "Last deployment was over 20 minutes ago. Proceeding with the workflow."
          fi
  deploy:
    name: Deploy to DEV V2
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: wait-if-not-over-20-minutes

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: echo "Success."
